import json
from bidi.algorithm import get_display
import unicodedata

def normalize_hebrew(text):
    """Normalize and format Hebrew text for proper RTL display."""
    return get_display(unicodedata.normalize("NFKC", text.strip()))

# Define the mapping dictionary
request_status_mapping = {
    1: normalize_hebrew("ממתין לתשלום"),
    2: normalize_hebrew("ממתין לקליטת תשלום"),
    3: normalize_hebrew("ממתין לקליטת מסמכים"),
    4: normalize_hebrew("ממתין לקליטת מסמכים"),
    5: normalize_hebrew("בדיקת מזכירות"),
    6: normalize_hebrew("ניתוב לדיין"),
    7: normalize_hebrew("ממתין לקביעת דיון"),
    8: normalize_hebrew("ממתין לדיון"),
    9: normalize_hebrew("ממתין להחלטה"),
    10: normalize_hebrew("ממתין להשלמת מסמכים"),
    11: normalize_hebrew("ממתין לתגובת צד א'"),
    12: normalize_hebrew("ממתין לתגובת צד ב'"),
    13: normalize_hebrew("ממתין לתגובת הצדדים"),
    14: normalize_hebrew("תיק מתנהל"),
    15: normalize_hebrew("ניתן פסק דין"),
    16: normalize_hebrew("סגור"),
    17: normalize_hebrew("מבוטל"),
    18: normalize_hebrew("קליטה הסתיימה"),
    19: normalize_hebrew("תקלה בקליטת מסמכים"),
    20: normalize_hebrew("ממתין לשינוי מועד דיון"),
    21: normalize_hebrew("ממתין לעיון ראשוני"),
    22: normalize_hebrew("ממתין לכתב תשובה"),
    23: normalize_hebrew("ממתין לפסק דין"),
    24: normalize_hebrew("אוחד"),
    25: normalize_hebrew("ממתין לתגובת הצדדים - עורר"),
    26: normalize_hebrew("ממתין לתגובת הצדדים - משיבה"),
    27: normalize_hebrew("תיק מוקפא / מעוכב"),
    28: normalize_hebrew("המשך הליכים בתיק"),
    29: normalize_hebrew("ממתין לביטול דיון")
}


# Define the mapping dictionary
request_type_mapping = {
    1: normalize_hebrew("בקשה לפתיחת תיק הוכחת נישואין"),
    2: normalize_hebrew("בקשה לפתיחת תיק בוררות לגירושין והפרדה"),
    3: normalize_hebrew("בקשה לפתיחת תיק גירושין בהסכמה"),
    4: normalize_hebrew("בקשה לפתיחת תיק צו קיום ירושה וצוואה"),
    5: normalize_hebrew("בקשה לפתיחת תיק הוכחת נישואין"),
    6: normalize_hebrew("בקשה לפתיחת תיק גירושין בהסכמה"),
    7: normalize_hebrew("בקשה לפתיחת תיק צו ירושה"),
    9: normalize_hebrew("בקשה לדחיית התביעה"),
    10: normalize_hebrew("בקשה לסגירת תיק"),
    11: normalize_hebrew("בקשה למתן החלטה"),
    12: normalize_hebrew("בקשה לקביעת דיון"),
    13: normalize_hebrew("בקשה לאיחוד תיקים"),
    14: normalize_hebrew("בקשה לתיקון החלטה/מסמך"),
    15: normalize_hebrew("בקשה למינוי בורר"),
    16: normalize_hebrew("בקשה לצילום תיק"),
    17: normalize_hebrew("בקשה דחופה"),
    18: normalize_hebrew("בקשה להתפטרות/החלפת ייצוג"),
    19: normalize_hebrew("בקשה כללית"),
    20: normalize_hebrew("בקשה לדחיית דיון"),
    21: normalize_hebrew("בקשה להקדמת מועד דיון"),
    22: normalize_hebrew("בקשה למינוי מגשרים"),
    23: normalize_hebrew("בקשה למתן ארכה"),
    24: normalize_hebrew("בקשת החזר אגרה/פקדון"),
    25: normalize_hebrew("בקשה לפתיחת תיק גירושין"),
    26: normalize_hebrew("בקשה להארכת מועד"),
    27: normalize_hebrew("בקשה לסעד זמני"),
    28: normalize_hebrew("בקשה לעיכוב ביצוע החלטה"),
    29: normalize_hebrew("בקשה לביצוע תחליף המצאה"),
    30: normalize_hebrew("בקשה להזמנת עדים"),
    31: normalize_hebrew("בקשה לעיון בתיק"),
    32: normalize_hebrew("בקשה לקבלת עותק תיק"),
    33: normalize_hebrew("בקשה לאחר סגירת תיק"),
    34: normalize_hebrew("פנייה לפתיחת תיק תביעה"),
    35: normalize_hebrew("בקשה לפתיחת תיק סכסוך משפחתי"),
    47: normalize_hebrew("בקשה לפתיחת תיק יישוב סכסוך"),
    48: normalize_hebrew("פנייה לפתיחת תיק תביעה שכנגד"),
    49: normalize_hebrew("פנייה לפתיחת תיק הודעה לצד ג'"),
    51: normalize_hebrew("בקשה לשינוי מועד דיון"),
    52: normalize_hebrew("בקשה לתיקון ליקויים"),
    54: normalize_hebrew("בקשה להוספה או למחיקה של בעלי דין"),
    55: normalize_hebrew("הודעה"),
    56: normalize_hebrew("בקשה למתן תוקף של פסק דין להסכם פשרה"),
    57: normalize_hebrew("בקשה אחרת על פי תקנות הסדר האזרחי"),
    58: normalize_hebrew("הגשת כתב הגנה עם פתיחת תיק תביעה שכנגד"),
    59: normalize_hebrew("הגשת כתב הגנה עם פתיחת תיק הודעה לצד ג'"),
    60: normalize_hebrew("בקשה לפתיחת תיק אישור חוזה נישואין"),
    61: normalize_hebrew("בקשה לפתיחת תיק הוכחת גירושין"),
    62: normalize_hebrew("בקשה לפתיחת תיק מזונות עידה"),
    63: normalize_hebrew("בקשה לפתיחת תיק מזונות אישה שכר דירה"),
    64: normalize_hebrew("בקשה לפתיחת תיק אישור גירושין"),
    65: normalize_hebrew("בקשה לפתיחת תיק מזונות ילדים"),
    66: normalize_hebrew("בקשה לפתיחת תיק מזונות ילדים שכר דירה"),
    67: normalize_hebrew("בקשה לפתיחת תיק משמורת ילדים"),
    68: normalize_hebrew("בקשה לפתיחת תיק משמורת ילדים מסירת קטינים"),
    69: normalize_hebrew("בקשה לפתיחת תיק משמורת ילדים פסק דין הצהרתי"),
    70: normalize_hebrew("בקשה לפתיחת תיק משמורת ילדים - בקשה לשינוי מקום המשמורת"),
    71: normalize_hebrew("בקשה לפתיחת תיק משמורת ילדים - סדרי ראיה ואירוח"),
    72: normalize_hebrew("בקשה לפתיחת תיק ביטול צו קיום צוואה"),
    73: normalize_hebrew("בקשה לפתיחת תיק ביטול צו ירושה"),
    74: normalize_hebrew("בקשה לפתיחת תיק צו ירושה משלים"),
    75: normalize_hebrew("בקשה לפתיחת תיק צו קיום צוואה"),
    76: normalize_hebrew("בקשה לפתיחת תיק תיקון צו ירושה"),
    77: normalize_hebrew("בקשה לפתיחת תיק צוואות וירושות- כל בקשה אחרת"),
    78: normalize_hebrew("בקשה לפתיחת תיק אפוטרופסות על חולים"),
    79: normalize_hebrew("בקשה לפתיחת תיק אפוטרופסות על קטינים"),
    80: normalize_hebrew("בקשה לפתיחת תיק אפוטרופסות על בגירים"),
    84: normalize_hebrew("בקשה לפתיחת תיק אפוטרופסות - בקשות שונות"),
    85: normalize_hebrew("בקשה לפתיחת תיק מזונות אישה החזר הוצאות"),
    86: normalize_hebrew("בקשה לפתיחת תיק מזונות אישה"),
    87: normalize_hebrew("בקשה לפתיחת תיק מזונות ילדים החזר הוצאות"),
    88: normalize_hebrew("בקשה לפתיחת תיק הגדלת מזונות ילדים"),
    89: normalize_hebrew("בקשה לפתיחת תיק ביטול מזונות"),
    90: normalize_hebrew("בקשה לפתיחת תיק צוואות וירושות - שונות"),
    91: normalize_hebrew("בקשה לפתיחת תיק המרת דת"),
    92: normalize_hebrew("בקשה לפתיחת תיק התנגדות / תיקון/ ביטול ירושה או צוואה"),
    93: normalize_hebrew("בקשה לפתיחת תיק מוהר"),
    94: normalize_hebrew("בקשה לפתיחת תיק רכוש בית"),
    95: normalize_hebrew("בקשה לפתיחת תיק היעדר מניעה"),
    96: normalize_hebrew("בקשה לפתיחת תיק עשיית צוואה בפני חבר בית הדין"),
    104: normalize_hebrew("בקשה לפתיחת תיק החזקת ילדים ומשמורת קטינים"),
    106: normalize_hebrew("בקשה לפתיחת תיק ערר חרבות ברזל - הוצאות מזכות"),
    107: normalize_hebrew("בקשה להארכת מועד להגשת ערר"),
    108: normalize_hebrew("בקשה לסילוק על הסף"),
    109: normalize_hebrew("בקשה לצירוף מסמכים"),
    110: normalize_hebrew("בקשה למחיקת ערר"),
    111: normalize_hebrew("בקשה לקביעת/ שינוי/ ביטול מועד דיון"),
    112: normalize_hebrew("בקשה לביטול / תיקון החלטה"),
    113: normalize_hebrew("בקשה לפסיקת הוצאות"),
    114: normalize_hebrew("בקשה לעדכון פרטי מייצג / עד"),
    115: normalize_hebrew("בקשה לדיון בדלתיים סגורות ו/ או איסור פרסום פרטי החלטה"),
    116: normalize_hebrew("בקשה לאיחוד עררים"),
    117: normalize_hebrew("בקשה למתן תוקף של החלטה לפשרה"),
    126: normalize_hebrew("בקשה להחלפת מייצג"),
    128: normalize_hebrew("בקשה לפתיחת תיק ערר קורונה - מענק הוצאות קבועות"),
    129: normalize_hebrew("בקשה לפתיחת תיק ערר קורונה - מענק פגיעה ממושכת"),
    130: normalize_hebrew("בקשה לפתיחת תיק ערר קורונה - מענק אומיקרון")
}
